"""initial schema

Revision ID: 9690788a9b50
Revises: 
Create Date: 2026-05-11 12:57:10.803705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9690788a9b50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('received_count', sa.Integer(), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('dropped_count', sa.Integer(), nullable=False),
    sa.Column('duplicates_count', sa.Integer(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.Column('by_owner', sa.JSON(), nullable=False),
    sa.Column('by_band', sa.JSON(), nullable=False),
    sa.Column('email_drafting_enabled', sa.Boolean(), nullable=False),
    sa.Column('llm_preferred', sa.Boolean(), nullable=False),
    sa.Column('meta_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payload_hash', name='uq_runs_payload_hash')
    )
    op.create_index(op.f('ix_runs_payload_hash'), 'runs', ['payload_hash'], unique=False)
    op.create_index(op.f('ix_runs_received_at'), 'runs', ['received_at'], unique=False)
    op.create_table('lead_results',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('lead_external_id', sa.String(length=64), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_name_normalised', sa.String(length=255), nullable=True),
    sa.Column('company_number_ch', sa.String(length=32), nullable=True),
    sa.Column('email_hash', sa.String(length=64), nullable=True),
    sa.Column('notes_hash', sa.String(length=64), nullable=True),
    sa.Column('notes_excerpt', sa.String(length=120), nullable=True),
    sa.Column('validation_passed', sa.Boolean(), nullable=False),
    sa.Column('email_valid', sa.Boolean(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of', sa.String(length=64), nullable=True),
    sa.Column('validation_issues', sa.JSON(), nullable=False),
    sa.Column('score_value', sa.Float(), nullable=False),
    sa.Column('score_band', sa.String(length=16), nullable=False),
    sa.Column('score_contributions', sa.JSON(), nullable=False),
    sa.Column('eligibility_eligible', sa.Boolean(), nullable=False),
    sa.Column('requires_manual_review', sa.Boolean(), nullable=False),
    sa.Column('eligibility_findings', sa.JSON(), nullable=False),
    sa.Column('routing_owner', sa.String(length=32), nullable=False),
    sa.Column('routing_queue', sa.String(length=32), nullable=False),
    sa.Column('routing_rationale', sa.Text(), nullable=False),
    sa.Column('email_subject', sa.Text(), nullable=True),
    sa.Column('email_body', sa.Text(), nullable=True),
    sa.Column('email_word_count', sa.Integer(), nullable=True),
    sa.Column('email_cta_count', sa.Integer(), nullable=True),
    sa.Column('email_used_disclaimer', sa.Boolean(), nullable=True),
    sa.Column('email_generator', sa.String(length=32), nullable=True),
    sa.Column('enrichment', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_results_company_name_normalised'), 'lead_results', ['company_name_normalised'], unique=False)
    op.create_index(op.f('ix_lead_results_company_number_ch'), 'lead_results', ['company_number_ch'], unique=False)
    op.create_index(op.f('ix_lead_results_email_hash'), 'lead_results', ['email_hash'], unique=False)
    op.create_index(op.f('ix_lead_results_is_duplicate'), 'lead_results', ['is_duplicate'], unique=False)
    op.create_index(op.f('ix_lead_results_lead_external_id'), 'lead_results', ['lead_external_id'], unique=False)
    op.create_index(op.f('ix_lead_results_processed'), 'lead_results', ['processed'], unique=False)
    op.create_index(op.f('ix_lead_results_processed_at'), 'lead_results', ['processed_at'], unique=False)
    op.create_index(op.f('ix_lead_results_routing_owner'), 'lead_results', ['routing_owner'], unique=False)
    op.create_index(op.f('ix_lead_results_run_id'), 'lead_results', ['run_id'], unique=False)
    op.create_index(op.f('ix_lead_results_score_band'), 'lead_results', ['score_band'], unique=False)
    op.create_table('run_errors',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('lead_external_id', sa.String(length=64), nullable=True),
    sa.Column('error_class', sa.String(length=128), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_errors_run_id'), 'run_errors', ['run_id'], unique=False)
    op.create_table('routing_overrides',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('lead_result_id', sa.String(length=32), nullable=False),
    sa.Column('original_owner', sa.String(length=32), nullable=False),
    sa.Column('corrected_owner', sa.String(length=32), nullable=False),
    sa.Column('operator_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_result_id'], ['lead_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_overrides_created_at'), 'routing_overrides', ['created_at'], unique=False)
    op.create_index(op.f('ix_routing_overrides_lead_result_id'), 'routing_overrides', ['lead_result_id'], unique=False)
    op.create_table('safety_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('lead_result_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_result_id'], ['lead_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_events_code'), 'safety_events', ['code'], unique=False)
    op.create_index(op.f('ix_safety_events_lead_result_id'), 'safety_events', ['lead_result_id'], unique=False)
    op.create_index(op.f('ix_safety_events_severity'), 'safety_events', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_safety_events_severity'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_lead_result_id'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_code'), table_name='safety_events')
    op.drop_table('safety_events')
    op.drop_index(op.f('ix_routing_overrides_lead_result_id'), table_name='routing_overrides')
    op.drop_index(op.f('ix_routing_overrides_created_at'), table_name='routing_overrides')
    op.drop_table('routing_overrides')
    op.drop_index(op.f('ix_run_errors_run_id'), table_name='run_errors')
    op.drop_table('run_errors')
    op.drop_index(op.f('ix_lead_results_score_band'), table_name='lead_results')
    op.drop_index(op.f('ix_lead_results_run_id'), table_name='lead_results')
    op.drop_index(op.f('ix_lead_results_routing_owner'), table_name='lead_results')
    op.drop_index(op.f('ix_lead_results_processed_at'), table_name='lead_results')
    op.drop_index(op.f('ix_lead_results_processed'), table_name='lead_results')
    op.drop_index(op.f('ix_lead_results_lead_external_id'), table_name='lead_results')
    op.drop_index(op.f('ix_lead_results_is_duplicate'), table_name='lead_results')
    op.drop_index(op.f('ix_lead_results_email_hash'), table_name='lead_results')
    op.drop_index(op.f('ix_lead_results_company_number_ch'), table_name='lead_results')
    op.drop_index(op.f('ix_lead_results_company_name_normalised'), table_name='lead_results')
    op.drop_table('lead_results')
    op.drop_index(op.f('ix_runs_received_at'), table_name='runs')
    op.drop_index(op.f('ix_runs_payload_hash'), table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
